# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e58272709c6f38d7e651f9f51599f9ca35256f12cbda3f923e709d045da593aa6f771dd18351d153ec5a03aa7db180bc74b5e20963ef50cac07d56328bf9ef6c

test:
  secret_key_base: c05d3ef2df19f28c94c59a70838806ed15f2b4ad120c26f605107497a6a361ed0937a9a5dcb5f53f06a4713228431489ead471413ec18b60ec82e3e9b552276b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
